#!/bin/bash

show=$(echo)
scriptemplacement="/home/tgautherot/Documents/Script/projetv2"

cat << 'EOF'
______________________________
 ____                                                                           __                                                                                                            __      
/\  _`\    __                                                                  /\ \                                                                                                __        /\ \__   
\ \ \L\ \ /\_\     __    ___   __  __     __    ___   __  __     __            \_\ \     __      ___     ____             ___ ___     ___     ___              ____    ___   _ __ /\_\  _____\ \ ,_\  
 \ \  _ <'\/\ \  /'__`\/' _ `\/\ \/\ \  /'__`\/' _ `\/\ \/\ \  /'__`\ _______  /'_` \  /'__`\  /' _ `\  /',__\  _______ /' __` __`\  / __`\ /' _ `\  _______  /',__\  /'___\/\`'__\/\ \/\ '__`\ \ \/  
  \ \ \L\ \\ \ \/\  __//\ \/\ \ \ \_/ |/\  __//\ \/\ \ \ \_\ \/\  __//\______\/\ \L\ \/\ \L\.\_/\ \/\ \/\__, `\/\______\/\ \/\ \/\ \/\ \L\ \/\ \/\ \/\______\/\__, `\/\ \__/\ \ \/ \ \ \ \ \L\ \ \ \_ 
   \ \____/ \ \_\ \____\ \_\ \_\ \___/ \ \____\ \_\ \_\ \____/\ \____\/______/\ \___,_\ \__/.\_\ \_\ \_\/\____/\/______/\ \_\ \_\ \_\ \____/\ \_\ \_\/______/\/\____/\ \____\\ \_\  \ \_\ \ ,__/\ \__\
    \/___/   \/_/\/____/\/_/\/_/\/__/   \/____/\/_/\/_/\/___/  \/____/         \/__,_ /\/__/\/_/\/_/\/_/\/___/           \/_/\/_/\/_/\/___/  \/_/\/_/         \/___/  \/____/ \/_/   \/_/\ \ \/  \/__/
                                                                                                                                                                                          \ \_\            
______________________________
EOF

Help() {
    echo "nmap is a command-line network exploration tool and security scanner."
    echo "gobuster is a tool for brute-forcing URLs and directories on a web server."
    echo "sqlmap is a tool for detecting and exploiting SQL injection vulnerabilities in web applications."
    echo "Use John the Ripper for password cracking."
    echo "Hydra is often used to attack protocols such as HTTP, FTP, SSH, and Telnet."
    echo "Utilise Station de décontamination pour réparer ta clé USB infectée."
}

while getopts ":h" choix; do
    case $choix in
        h)
            Help
            exit
            ;;
        \?)
            echo "Error: Invalid option"
            exit
            ;;
    esac
done

sleep 2
echo -e "\e[39m"
echo -n "Que souhaite-tu faire aujourd'hui ?"
echo ""
echo "1. Nmap"
echo "2. Gobuster"
echo "3. SQLmap"
echo "4. John the Ripper"
echo "5. Hydra"
echo "6. Station de décontamination"
echo "7. Relancer"
echo "8. Exit"
echo -n "Votre choix : "
read -r choix

case "$choix" in
    1)
        apt list nmap
        sleep 5
        sudo apt install nmap
        echo "Entrez le réseau à scanner (ex: 192.168.1.0/24) :"
        read -r network
        if [ -z "$network" ]; then
            echo "Réseau invalide"
        else
            nmap "$network"
            exit 0
        fi
        ;;
    2)
        apt list gobuster
        sleep 5
        sudo apt install gobuster
        echo "Quelle URL souhaitez-vous utiliser ?"
        read -r url
        if [ -z "$url" ]; then
            echo "URL invalide"
        else
            gobuster dir -u "$url" -w /usr/share/directory.txt
            dig "$url"
        fi
        ;;
    3)
        apt list sqlmap
        sleep 5
        sudo apt install sqlmap
        echo "Quel site PHP souhaitez-vous injecter ?"
        read -r url
        if [ -z "$url" ]; then
            echo "URL invalide"
        else
            sqlmap -u "$url"
        fi
        ;;
    4)
        apt list john
        sleep 5
        sudo apt-get install john
        echo "Vous avez choisi John the Ripper."
        echo "Veuillez entrer le chemin vers le fichier de hash :"
        read -r hash_file
        echo "Veuillez entrer le chemin d’accès au fichier de wordlist :"
        read -r wordlist_file
        john "$hash_file" --wordlist="$wordlist_file"
        ;;
    5)
        apt list hydra-gtk
        sleep 5
        apt-get install hydra-gtk
        echo "Définissez le nom d’utilisateur pour l’attaque :"
        read -r username
        if [ -z "$username" ]; then
            echo "Nom d’utilisateur invalide"
        fi
        echo "Définissez le fichier de mots de passe pour l’attaque :"
        read -r password_file
        if [ -z "$password_file" ]; then
            echo "Fichier de mots de passe invalide"
        fi
        echo "Définissez la cible pour l’attaque :"
        read -r target
        if [ -z "$target" ]; then
            echo "Cible invalide"
        else
            hydra -l "$username" -P "$password_file" "$target"
        fi
        ;;
    6)
        echo "Station de décontamination en cours..."
        sudo apt install -y clamav # Installation de ClamAV si non installé
        sudo freshclam # Mise à jour de la base de données des virus

        echo "Veuillez insérer votre clé USB et indiquer son point de montage (ex: /media/user/USB) :"
        read -r usb_mount

        if [ -d "$usb_mount" ]; then
            echo "Analyse de la clé USB en cours..."
            sudo clamscan -r --remove=yes "$usb_mount"

            echo "Décontamination terminée !"
        else
            echo "Point de montage invalide. Vérifiez que la clé USB est bien connectée."
        fi
        ;;
    7)
        bash "$scriptemplacement"
        ;;
    8)
        exit
        ;;
    *)
        echo "Choix invalide"
        sleep 5s
        bash "$scriptemplacement"
        ;;
esac
